import Foundation
import PackagePlugin

/// Embeds text resources into `WispCore` as Swift string constants at build time, so each is a plain
/// file in the source tree and the product stays one binary with nothing to ship beside it:
/// `Resources/system-prompt.md` as `SystemPromptText.text`, `Resources/measurements.json` as
/// `MeasurementsText.text`, `Resources/multiplexers.txt` as `MultiplexersText.text`, and
/// `Resources/risk-examples.tsv` as `RiskExamplesText.text`, and `Resources/risk-default.json` (the shipped
/// risk classifier, its model in base64) as `RiskDefaultText.text`, and `Resources/personal-default.json` (the
/// personal-data classifier, likewise) as `PersonalDefaultText.text`, and `Resources/subject-kinds.json` (the default
/// subject kinds of facts) as `SubjectKindsText.text`, and the shell completion scripts in `Resources/completions/`
/// (`_wisp`, `wisp.bash`, `wisp.fish`) as `ZshCompletionText.text`, `BashCompletionText.text`, and
/// `FishCompletionText.text`. The text goes into a raw multi-line literal, so it needs no escaping; its delimiter
/// has more `#`s than any `"""#…` or `\#…` in the text, so nothing in it can end the literal early or interpolate.
///
/// It also writes `BuildInfo` before every build (a prebuild command, since the commit changes without any
/// input file changing): the commit `git` reports for the package's repository, whether the working tree
/// has changes, and whether `WISP_RELEASE=1` is set, which only `scripts/release` does. `git` missing, a
/// source tree without a repository, or a plugin sandbox that refuses it all leave the commit `nil`. The file is
/// rewritten only when its content changes, so an unchanged state costs no recompile.
@main
struct EmbedSystemPrompt: BuildToolPlugin {
    /// The shell that turns a text file into Swift; `$1` is the input, `$2` the output, `$3` the type.
    /// The literal's delimiter is one `#` more than any run the text could end it with or interpolate with: a text
    /// holding `"""#` or `\#` (`\#(` would be an interpolation, `\#n` an escape) gets `##`, and so on.
    static let script = """
        set -eu
        hashes='#'
        while grep -qF "\\"\\"\\"$hashes" "$1" || grep -qF "\\\\$hashes" "$1"; do hashes="$hashes#"; done
        {
            printf '// Generated from %s by the EmbedSystemPrompt plugin. Do not edit.\\n' "$(basename "$1")"
            printf 'enum %s {\\n    static let text = %s\"\"\"\\n' "$3" "$hashes"
            cat "$1"
            printf '\"\"\"%s\\n}\\n' "$hashes"
        } > "$2"
        """

    /// The shell that writes `BuildInfo.swift`; `$1` is the output directory, `$2` a directory in the repository.
    /// `GIT_OPTIONAL_LOCKS=0` keeps `git status` from refreshing the index, which a sandbox would refuse.
    static let buildInfoScript = """
        set -u
        export GIT_OPTIONAL_LOCKS=0
        commit=nil; modified=false; release=false
        if hash=$(git -C "$2" rev-parse --short=7 HEAD 2>/dev/null) && [ -n "$hash" ]; then
            commit="\\"$hash\\""
            if [ -n "$(git -C "$2" status --porcelain --untracked-files=no 2>/dev/null)" ]; then modified=true; fi
        fi
        if [ "$3" = 1 ]; then release=true; fi
        mkdir -p "$1"
        out="$1/BuildInfo.swift"
        {
            printf '// Generated by the EmbedSystemPrompt plugin before every build. Do not edit.\\n'
            printf 'enum BuildInfo {\\n'
            printf '    static let commit: String? = %s\\n' "$commit"
            printf '    static let modified = %s\\n' "$modified"
            printf '    static let release = %s\\n}\\n' "$release"
        } > "$out.tmp"
        if cmp -s "$out.tmp" "$out"; then rm -f "$out.tmp"; else mv "$out.tmp" "$out"; fi
        """

    /// The resources embedded, as file name and Swift type.
    static let resources = [
        ("system-prompt.md", "SystemPromptText"), ("measurements.json", "MeasurementsText"),
        ("multiplexers.txt", "MultiplexersText"), ("risk-examples.tsv", "RiskExamplesText"),
        ("risk-default.json", "RiskDefaultText"), ("personal-default.json", "PersonalDefaultText"),
        ("subject-kinds.json", "SubjectKindsText"), ("completions/_wisp", "ZshCompletionText"),
        ("completions/wisp.bash", "BashCompletionText"), ("completions/wisp.fish", "FishCompletionText"),
    ]

    func createBuildCommands(context: PluginContext, target: Target) throws -> [Command] {
        guard let target = target as? SourceModuleTarget else { return [] }
        let info = context.pluginWorkDirectoryURL.appending(path: "build-info")
        let infoCommand = Command.prebuildCommand(
            displayName: "Record the build's commit",
            executable: URL(filePath: "/bin/sh"),
            arguments: [
                "-c", Self.buildInfoScript, "build-info", info.path(), target.directoryURL.path(),
                ProcessInfo.processInfo.environment["WISP_RELEASE"] ?? "",
            ],
            outputFilesDirectory: info
        )
        return [infoCommand]
            + Self.resources.map { file, type in
                let input = target.directoryURL.appending(path: "Resources/\(file)")
                let output = context.pluginWorkDirectoryURL.appending(path: "\(type).swift")
                return .buildCommand(
                    displayName: "Embed \(file)",
                    executable: URL(filePath: "/bin/sh"),
                    arguments: ["-c", Self.script, "embed-resource", input.path(), output.path(), type],
                    inputFiles: [input],
                    outputFiles: [output]
                )
            }
    }
}
