import Foundation

/// wisp's shell completion scripts and where `wisp completions install` puts them.
///
/// The scripts are generated by swift-argument-parser from wisp's own command tree, committed as
/// `Resources/completions/` (`_wisp`, `wisp.bash`, `wisp.fish`) with a marker line, and embedded at build time by
/// the `EmbedSystemPrompt` plugin, so the binary carries them and prints them with no file beside it. The gate
/// regenerates them from the built binary and fails when the committed files differ (`scripts/check completions`
/// rewrites them). Installing writes only to a path that is empty or holds a file carrying the marker, so a file
/// the person wrote is never replaced.
public enum ShellCompletions {
    /// A shell wisp has a completion script for.
    public enum Shell: String, CaseIterable, Sendable, Equatable {
        /// zsh, through `compinit` and `fpath`.
        case zsh
        /// bash, through bash-completion's per-user directory.
        case bash
        /// fish, through its per-user completions directory.
        case fish
    }

    /// The start of the marker line every embedded script carries, which `scripts/check completions` writes.
    public static let markerPrefix = "# wisp completions:"

    /// How many lines from the top a file is searched for the marker.
    static let markerWindow = 5

    /// The embedded script for `shell`, without its final newline (print adds it back).
    ///
    /// - Parameter shell: The shell.
    /// - Returns: The script.
    public static func script(_ shell: Shell) -> String {
        switch shell {
        case .zsh: ZshCompletionText.text
        case .bash: BashCompletionText.text
        case .fish: FishCompletionText.text
        }
    }

    /// The shell `$SHELL` names, by its last path component (`/bin/zsh`, `/opt/homebrew/bin/fish`).
    ///
    /// - Parameter path: The value of `$SHELL`, nil when unset.
    /// - Returns: The shell, or nil when it is unset or not one wisp has a script for.
    public static func detect(shellPath path: String?) -> Shell? {
        guard let path, !path.isEmpty else { return nil }
        return Shell(rawValue: URL(filePath: path).lastPathComponent)
    }

    /// Whether `text` is a wisp completion script: it carries the marker line near the top.
    ///
    /// - Parameter text: The file's contents.
    /// - Returns: True for wisp's own file.
    public static func isOwn(_ text: String) -> Bool {
        text.split(separator: "\n", maxSplits: markerWindow, omittingEmptySubsequences: false).prefix(markerWindow)
            .contains { $0.hasPrefix(markerPrefix) }
    }

    /// The per-user file `shell` loads wisp's completions from.
    ///
    /// zsh: `~/.zsh/completions/_wisp`, a directory to put on `fpath`. bash: bash-completion's user directory,
    /// `$BASH_COMPLETION_USER_DIR/completions/wisp` (its first entry), else
    /// `${XDG_DATA_HOME:-~/.local/share}/bash-completion/completions/wisp`. fish:
    /// `${XDG_CONFIG_HOME:-~/.config}/fish/completions/wisp.fish`. An XDG variable that is empty or relative is
    /// ignored, as the specification says.
    ///
    /// - Parameters:
    ///   - shell: The shell.
    ///   - environment: The process environment.
    ///   - home: The home directory: `$HOME` when the caller has none of its own.
    /// - Returns: The file.
    public static func installURL(_ shell: Shell, environment: [String: String], home: URL) -> URL {
        /// A variable's value when it is an absolute path.
        func absolute(_ key: String) -> URL? {
            guard let value = environment[key]?.split(separator: ":").first.map(String.init), value.hasPrefix("/")
            else { return nil }
            return URL(filePath: value, directoryHint: .isDirectory)
        }
        switch shell {
        case .zsh:
            return home.appending(path: ".zsh/completions/_wisp")
        case .bash:
            let base =
                absolute("BASH_COMPLETION_USER_DIR")
                ?? (absolute("XDG_DATA_HOME") ?? home.appending(path: ".local/share", directoryHint: .isDirectory))
                .appending(path: "bash-completion", directoryHint: .isDirectory)
            return base.appending(path: "completions/wisp")
        case .fish:
            let base = absolute("XDG_CONFIG_HOME") ?? home.appending(path: ".config", directoryHint: .isDirectory)
            return base.appending(path: "fish/completions/wisp.fish")
        }
    }

    /// The home directory to install under: `$HOME`, else the account's.
    ///
    /// - Parameter environment: The process environment.
    /// - Returns: The directory.
    public static func home(environment: [String: String]) -> URL {
        if let home = environment["HOME"], home.hasPrefix("/") {
            return URL(filePath: home, directoryHint: .isDirectory)
        }
        return FileManager.default.homeDirectoryForCurrentUser
    }

    /// What installing did.
    public enum Outcome: String, Equatable, Sendable {
        /// The file did not exist and was written.
        case written
        /// An older wisp script was there and was replaced.
        case replaced
        /// The same script was already there.
        case unchanged
    }

    /// Why a script could not be installed.
    public enum Failure: Error, CustomStringConvertible, Equatable {
        /// No shell was named and `$SHELL` names none wisp has a script for.
        case unknownShell(String?)
        /// Something other than a wisp script is at the path.
        case foreign(path: String)
        /// The file or its directory could not be written.
        case unwritable(path: String, reason: String)

        /// The message shown to the person.
        public var description: String {
            switch self {
            case .unknownShell(let shell):
                "cannot tell the shell from $SHELL (\(shell ?? "unset")); name it: wisp completions install zsh|bash|fish"
            case .foreign(let path):
                "\(path) exists and is not a wisp completion script; move it aside, or print the script with "
                    + "'wisp completions <shell>' and install it yourself"
            case .unwritable(let path, let reason): "cannot write \(path): \(reason)"
            }
        }
    }

    /// Writes `shell`'s script to `url`, creating its directory, unless something other than a wisp script is there.
    ///
    /// - Parameters:
    ///   - shell: The shell.
    ///   - url: The file, from `installURL`.
    /// - Returns: What was done.
    /// - Throws: `Failure.foreign` for a file that is not wisp's, `Failure.unwritable` when writing fails.
    public static func install(_ shell: Shell, at url: URL) throws -> Outcome {
        let content = script(shell) + "\n"
        let manager = FileManager.default
        var isDirectory: ObjCBool = false
        var outcome = Outcome.written
        if manager.fileExists(atPath: url.path, isDirectory: &isDirectory) {
            guard !isDirectory.boolValue, let data = try? Data(contentsOf: url),
                let existing = String(data: data, encoding: .utf8), isOwn(existing)
            else { throw Failure.foreign(path: url.path) }
            if existing == content { return .unchanged }
            outcome = .replaced
        }
        do {
            try manager.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
            try Data(content.utf8).write(to: url, options: .atomic)
        } catch {
            throw Failure.unwritable(path: url.path, reason: error.localizedDescription)
        }
        return outcome
    }

    /// How to start using a script installed at `url`, as lines to print.
    ///
    /// - Parameters:
    ///   - shell: The shell.
    ///   - url: Where it was installed.
    ///   - environment: The process environment; zsh's `FPATH`, when exported, shows whether the directory is on
    ///     `fpath` already.
    ///   - home: The home directory, for showing paths under it as `~`.
    /// - Returns: The lines.
    public static func activation(_ shell: Shell, at url: URL, environment: [String: String], home: URL) -> [String] {
        let directory = url.deletingLastPathComponent().standardizedFileURL.path
        let shown = tilde(directory, home: home)
        switch shell {
        case .zsh:
            let onPath = (environment["FPATH"] ?? "").split(separator: ":").contains {
                URL(filePath: String($0)).standardizedFileURL.path == directory
            }
            if onPath {
                return ["Start a new zsh (exec zsh) to load it; if the old completions persist, remove ~/.zcompdump."]
            }
            return [
                "Unless \(shown) is already on your fpath, add these lines to ~/.zshrc, before any compinit there:",
                "  fpath+=(\(shown))",
                "  autoload -U compinit; compinit",
                "then start a new zsh (exec zsh).",
            ]
        case .bash:
            return [
                "bash-completion 2 loads it on demand in new shells (Homebrew: brew install bash-completion@2, and "
                    + "source its bash_completion.sh from ~/.bash_profile).",
                "Without bash-completion, add to ~/.bashrc: source \(tilde(url.path, home: home))",
            ]
        case .fish:
            return ["fish loads it in new sessions."]
        }
    }

    /// `path` with the home directory written `~`.
    ///
    /// - Parameters:
    ///   - path: The path.
    ///   - home: The home directory.
    /// - Returns: The path to show.
    static func tilde(_ path: String, home: URL) -> String {
        let root = home.standardizedFileURL.path
        guard !root.isEmpty, root != "/", path == root || path.hasPrefix(root + "/") else { return path }
        return "~" + path.dropFirst(root.count)
    }
}

/// The candidates wisp's dynamic shell completions offer, each read from local files only (no network, no model),
/// so a Tab press stays instant. swift-argument-parser runs these inside `wisp` when the shell asks.
public enum CompletionCandidates {
    /// Models for `--model`: Apple's two and the configured default. Listing what each local backend serves would
    /// ask Ollama and the other servers over the network, so it is left to `wisp models`.
    ///
    /// - Parameter config: The effective configuration, nil when `config.json` does not load.
    /// - Returns: The names.
    public static func models(config: Config.Resolved?) -> [String] {
        var names = [ModelSelection.system.description, ModelSelection.privateCloud.description]
        if let model = config?.model.description, !names.contains(model) { names.append(model) }
        return names
    }

    /// Models for `wisp models enable`: those `models.disabled` names.
    ///
    /// - Parameter config: The effective configuration, nil when `config.json` does not load.
    /// - Returns: The names.
    public static func disabledModels(config: Config.Resolved?) -> [String] {
        (config?.disabledModels ?? []).map(\.description)
    }

    /// Tools for `--tool`: the built-ins and the user's own.
    ///
    /// - Parameter config: The effective configuration, nil when `config.json` does not load.
    /// - Returns: The names.
    public static func tools(config: Config.Resolved?) -> [String] {
        ToolRegistry.builtInNames + (config?.customTools ?? []).map(\.name)
    }

    /// Settings for `wisp config get|set|unset`: those `wisp config list` shows.
    ///
    /// - Parameter home: wisp's home.
    /// - Returns: The dotted paths.
    public static func settings(home: Home) -> [String] {
        ConfigSettings.listed(in: try? Data(contentsOf: home.configFile)).map(\.path)
    }

    /// Ids of standing approvals, for `wisp approvals revoke`.
    ///
    /// - Parameter home: wisp's home.
    /// - Returns: The ids, newest first.
    public static func approvals(home: Home) async -> [String] {
        await ApprovalStore(url: home.approvalsFile).all.map(\.id)
    }

    /// Ids of requests waiting in `~/.wisp/pending`: commands for `wisp approvals approve|deny`, facts for
    /// `wisp facts keep|drop`.
    ///
    /// - Parameters:
    ///   - kind: The kind of request.
    ///   - home: wisp's home.
    /// - Returns: The ids, oldest first.
    public static func pending(_ kind: PendingApprovals.Kind, home: Home) -> [String] {
        PendingApprovals(home: home).waiting(kind).map(\.id)
    }
}
